cicksblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(max=255)])
    content = TextAreaField("Content", validators=[DataRequired(), Length(max=2000)])
    submit = SubmitField("Submit")

cicksblog/main/routes.py
from cicksblog.models import Post
from flask import render_template, request, Blueprint

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    # determine the current page
    page = request.args.get("page", 1, type=int)
    # query all data posts with pagination order by date posted
    posts = Post.query.order_by(Post.id.desc()).paginate(page=page, per_page=5)

    return render_template("home.html", title="Home", posts=posts)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

cicksblog/posts/routes.py
from cicksblog import db
from cicksblog.models import Post
from cicksblog.posts.forms import PostForm
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import current_user, login_required

# from flask import abort

posts = Blueprint("posts", __name__)


@posts.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    post_form = PostForm()

    if post_form.validate_on_submit():
        # instance PostModel
        post = Post(
            title=post_form.title.data,
            content=post_form.content.data,
            author=current_user,
        )
        # insert post to database
        db.session.add(post)
        db.session.commit()
        # make a flash message when create post successfully
        flash("Your post has been created!🙂", "success")
        # go back to main page
        return redirect(url_for("main.home"))

    return render_template(
        "post.html", title="Create Post", legend="Create New Post", form=post_form
    )


@posts.route("/post/<int:post_id>/edit", methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    # get the current post
    post = Post.query.get_or_404(post_id)
    # check post author
    if post.author.id != current_user.id:
        # return abort(403)
        flash("You are not allowed to edit this post!🤔", "warning")
        return redirect(url_for("posts.current_post", post_id=post.id))
    # instance PostForm
    post_form = PostForm()
    # when form is submitted
    if post_form.validate_on_submit():
        # change with new title and content
        post.title = post_form.title.data
        post.content = post_form.content.data
        # commit data to database
        db.session.commit()
        # flash message when update complete
        flash("Your post has been updated!😉", "success")
        # go back to current post
        return redirect(url_for("posts.current_post", post_id=post.id))
    elif request.method == "GET":
        # populating field with existing data
        post_form.title.data = post.title
        post_form.content.data = post.content

    return render_template(
        "post.html", title="Edit Post", legend="Edit This Post", form=post_form
    )


@posts.route("/post/<int:post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(post_id):
    # get the current post
    post = Post.query.get_or_404(post_id)
    # check post author
    if post.author.id != current_user.id:
        # return abort(403)
        flash("You are not allowed to delete this post!🤔", "warning")
        return redirect(url_for("posts.current_post", post_id=post.id))
    # delete post from database
    db.session.delete(post)
    db.session.commit()
    # flash message when delete complete
    flash("Your post has been deleted!😮", "success")

    return redirect(url_for("main.home"))


@posts.route("/post/<int:post_id>")
def current_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("current_post.html", title="Current Post", post=post)

cicksblog/users/routes.py
from cicksblog import db, bcrypt
from cicksblog.models import User, Post
from cicksblog.users.utilities import save_pict, send_token_email
from cicksblog.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateForm,
    ResetRequestForm,
    ResetPasswordForm,
)
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
import datetime


users = Blueprint("users", __name__)


@users.route("/registration", methods=["GET", "POST"])
def registration():
    # check if user is already login
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    regist_form = RegistrationForm()

    if regist_form.validate_on_submit():
        # hashed the password
        hashed_password = bcrypt.generate_password_hash(
            regist_form.password.data
        ).decode("utf-8")
        # instance UserModel
        user = User(
            username=regist_form.username.data,
            email=regist_form.email.data,
            phone_number=regist_form.phone_number.data,
            password=hashed_password,
        )
        # insert user to database
        db.session.add(user)
        db.session.commit()
        # make a flash message when registration successfully
        flash("Your account has been craeted!🤗", "success")
        # redirecting to login
        return redirect(url_for("users.login"))

    return render_template("registration.html", title="Registration", form=regist_form)


@users.route("/login", methods=["GET", "POST"])
def login():
    # check if user is already login
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    login_form = LoginForm()

    if login_form.validate_on_submit():
        # check user in database
        user = User.query.filter_by(username=login_form.username.data).first()
        # if user is found in database
        if user:
            # check password
            password = bcrypt.check_password_hash(
                user.password, login_form.password.data
            )
            # if password is true
            if password:
                # set the login and session
                login_user(
                    user,
                    remember=login_form.remember.data,
                    duration=datetime.timedelta(seconds=3600),
                )
                # determine the next page
                next_page = request.args.get("next")
                # make a flash message when login successfully
                flash(f"Welcome To Cicks Blog, {login_form.username.data}!😇", "success")
                # redirecting to main.home or next page
                return (
                    redirect(next_page) if next_page else redirect(url_for("main.home"))
                )
            # if password is false
            else:
                flash("Invalid password!😢", "error")
        # if user not found in database
        else:
            flash("Invalid username or password!😢", "error")
    # go back to login form
    return render_template("login.html", title="Login", form=login_form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.login"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    update_form = UpdateForm()

    if update_form.validate_on_submit():
        # check if user update his picture profile
        if update_form.user_pict.data:
            pict_file = save_pict(update_form.user_pict.data)
            current_user.user_pict = pict_file
        # change with new username, email, and phone number
        current_user.username = update_form.username.data
        current_user.email = update_form.email.data
        current_user.phone_number = update_form.phone_number.data
        # commit data to database
        db.session.commit()
        # flash message when complete
        flash("Your account has been updated!😉", "success")
        # go back to account route
        return redirect(url_for("users.account"))
    # when form is not submitted
    elif request.method == "GET":
        # populating field with existing data
        update_form.username.data = current_user.username
        update_form.email.data = current_user.email
        update_form.phone_number.data = current_user.phone_number

    # set profile picture location
    img_profile = url_for("static", filename="img/" + current_user.user_pict)

    return render_template(
        "account.html", title="My Account", form=update_form, img=img_profile
    )


@users.route("/account/<string:username>", methods=["GET", "POST"])
def account_info(username):
    # determine user from username
    user = User.query.filter_by(username=username).first_or_404()
    # check if user is already login
    if current_user.is_authenticated:
        # jika parameter username sama dengan username yang sedang login,
        # maka beri akses untuk mengedit datanya
        if user.username == current_user.username:
            return redirect(url_for("users.account"))

    # set profile picture location
    img_profile = url_for("static", filename="img/" + user.user_pict)

    return render_template(
        "account_info.html", title="Account Info", user=user, img=img_profile
    )


@users.route("/user/<string:username>")
def user_posts(username):
    # determine the current page
    page = request.args.get("page", 1, type=int)
    # determine user from username
    user = User.query.filter_by(username=username).first_or_404()
    # query all data posts from user with pagination order by date posted
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.date_posted.desc())
        .paginate(page=page, per_page=3)
    )

    return render_template(
        "user_posts.html",
        title=f"{user.username} Posts",
        user=user,
        posts=posts,
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    # check if user is already login
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    req_form = ResetRequestForm()

    if req_form.validate_on_submit():
        user = User.query.filter_by(email=req_form.email.data).first()
        send_token_email(user)
        flash(
            f'An email has been sent to  "{req_form.email.data}".\nCheck it to reset your password!🥰',
            "info",
        )
        return redirect(url_for("users.login"))

    return render_template("reset_request.html", title="Reset Password", form=req_form)


@users.route("/reset_password/<string:token>", methods=["GET", "POST"])
def reset_password(token):
    # check if user is already login
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))

    user = User.token_verification(token)

    if user is None:
        flash("The token you entered is incorrect or has expired!😌", "error")
        return redirect(url_for("users.reset_request"))

    reset_form = ResetPasswordForm()

    if reset_form.validate_on_submit():
        # hashed the password and reset new password from user
        user.password = bcrypt.generate_password_hash(reset_form.password.data).decode(
            "utf-8"
        )
        # insert user to database
        db.session.commit()
        # make a flash message when registration successfully
        flash("Your password has been reset, you can login now!😇", "success")
        # redirecting to login
        return redirect(url_for("users.login"))

    return render_template(
        "reset_password.html", title="Reset Password", form=reset_form
    )

cicksblog/templates/about.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="display-4 mb-2">About</h1>
<p class="text-justify">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam est quod animi voluptates dolorum libero minima?
    Libero nobis quisquam distinctio nostrum, est, officiis perspiciatis ad, soluta sit itaque vitae cumque.
</p>

{% endblock content %}

cicksblog/templates/account.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
    <div class="media">
        <img class="rounded-circle shadow account-img" src="{{ img }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <h6 class="text-secondary mb-1">{{ current_user.email }}</h6>
            <p class="text-secondary mb-1">{{ current_user.phone_number }}</p>
        </div>
    </div>

    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}

        <legend class="account-heading mb-4">Account Info</legend>

        <div class="form-group">
            {{ form.username.label(class="form-control-label") }}
            {% if form.username.errors %}
            {{ form.username(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.username(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.email.label(class="form-control-label") }}
            {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.phone_number.label(class="form-control-label") }}
            {% if form.phone_number.errors %}
            {{ form.phone_number(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.phone_number.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.phone_number(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.user_pict.label() }}
            {{ form.user_pict(class="form-control-file") }}
            {% if form.user_pict.errors %}
            {% for error in form.user_pict.errors %}
            <span class="text-danger d-block mt-2 mb-4">{{ error }}</span>
            {% endfor %}
            {% endif %}
        </div>

        <div class="form-group mt-4">
            {{ form.submit(class="btn btn-secondary") }}
        </div>
    </form>
</div>

{% endblock content %}

cicksblog/templates/account_info.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
    <div class="media">
        <div class="media-body text-center">
            <img class="rounded-circle shadow account-info-img" src="{{ img }}">
            <h2 class="account-heading">{{ user.username }}</h2>
            <h6 class="text-secondary mb-1">{{ user.email }}</h6>
            <p class="text-secondary mb-1">{{ user.phone_number }}</p>
        </div>
    </div>
</div>

{% endblock content %}

cicksblog/templates/current_post.html
{% extends 'layout.html' %}

{% block content %}

<article class="media content-section">
    {% if post.author.id == current_user.id %}
    <a href="{{ url_for('users.account') }}" title="click to see your profile">
        <img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
    </a>
    {% else %}
    <a href="{{ url_for('users.account_info', username=post.author.username) }}" title="click to see this profile">
        <img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
    </a>
    {% endif %}
    <div class="media-body">
        <div class="article-metadata mb-2">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            <small class="text-muted">{{ post.date_posted.strftime('%A, %d %b %Y.') }}</small>
            {% if post.author.id == current_user.id %}
            <div class="action my-2">
                <a role="button" id="btn-edit" class="btn btn-primary btn-sm mr-2"
                    href="{{url_for('posts.edit_post', post_id=post.id)}}">
                    Edit Post
                </a>
                <a role="button" id="btn-delete" class="btn btn-danger btn-sm mr-2"
                    href="{{url_for('posts.delete_post', post_id=post.id)}}">
                    Delete Post
                </a>
            </div>
            {% endif %}
        </div>
        <h3 class="article-title">{{ post.title }}</h3>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>

{% endblock content %}

cicksblog/templates/home.html
{% extends 'layout.html' %}

{% block content %}

<!-- content -->
<h1 class="display-4 mb-2">Welcome To Cick's Blog!</h1>
{% for post in posts.items %}
<article class="media content-section">
	{% if post.author.id == current_user.id %}
	<a href="{{ url_for('users.account') }}" title="click to see your profile">
		<img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
	</a>
	{% else %}
	<a href="{{ url_for('users.account_info', username=post.author.username) }}" title="click to see this profile">
		<img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
	</a>
	{% endif %}
	<div class="media-body">
		<div class="article-metadata mb-2">
			<a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">
				{{ post.author.username }}
			</a>
			<small class="text-muted">{{ post.date_posted.strftime('%A, %d %b %Y.') }}</small>
		</div>
		<h3><a class="article-title" href="{{ url_for('posts.current_post', post_id=post.id) }}">{{ post.title }}</a>
		</h3>
		<p class="article-content">{{ post.content }}</p>
	</div>
</article>
{% endfor %}

<!-- pagination -->
<nav class="mt-2 mb-4" aria-label="Page navigation example">
	<ul class="pagination justify-content-center">
		{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
		{% if page_num %}
		{% if page_num == posts.page %}
		<li class="page-item active" aria-current="page">
			<a class="page-link" href="{{ url_for('main.home', page=page_num) }}">
				{{ page_num }}
				<span class="sr-only">(current)</span>
			</a>
		</li>
		{% else %}
		<li class="page-item">
			<a class="page-link" href="{{ url_for('main.home', page=page_num) }}">
				{{ page_num }}
			</a>
		</li>
		{% endif %}
		{% endif %}
		{% endfor %}
	</ul>
</nav>

{% endblock content %}

cicksblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.css')}}" />
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/all.min.css')}}" />
	<!-- External CSS -->
	<link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" />
	<!-- Title -->
	<title>{{ title }} | Cick's Blog</title>
</head>

<body>
	<!-- header -->
	<header class="site-header">
		<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
			<div class="container">
				<a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">
					<i class="fas fa-dove"></i>
					Cick's blog
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
					aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarToggle">
					<div class="navbar-nav mr-auto">
						<a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
						<a class="nav-item nav-link" href="{{ url_for('main.about') }}">
							About
						</a>
					</div>
					<!-- Navbar Right Side -->
					<div class="navbar-nav">
						{% if not current_user.is_authenticated %}
						<a class="nav-item nav-link" href="{{ url_for('users.registration') }}">
							<i class="fas fa-user-plus mr-1"></i>
							Registration
						</a>
						<a class="nav-item nav-link" href="{{ url_for('users.login') }}">
							<i class="fas fa-sign-in-alt mr-1"></i>
							Login
						</a>
						{% else %}
						<a class="nav-item nav-link" href="{{ url_for('posts.create_post') }}">
							<i class="fas fa-plus-circle mr-1"></i>
							New Post
						</a>
						<a class="nav-item nav-link" href="{{ url_for('users.account') }}">
							<i class="fas fa-user-astronaut mr-1"></i>
							Account
						</a>
						<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">
							<i class="fas fa-sign-out-alt mr-1"></i>
							Logout
						</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
	</header>

	<!-- main -->
	<main role="main" class="container">
		<div class="row">
			<!-- main content section -->
			<div class="col-md-8">
				{% with messages = get_flashed_messages(with_categories=True) %}
				{% if messages %}
				{% for category, message in messages %}
				<div class="flash-data" data-flash="{{ message }}" data-category="{{ category }}"></div>
				{% endfor %}
				{% endif %}
				{% endwith %}
				{% block content %} {% endblock content %}
			</div>
			<!-- side content section-->
			<div class="col-md-4">
				<div class="content-section p-4">
					<h3 class="text-center">
						<i class="far fa-heart"></i>
						Stories
					</h3>
					<div class="stories mb-4 text-center">
						<p class="mb-0">
							“What lies behind us and what lies before us are
							tiny matters compared to what lies within us.”
						</p>
						<small>- Ralph Waldo Emerson</small>
					</div>
					<ul class="list-group">
						<li class="list-group-item list-group-item-light">
							Latest Posts
						</li>
						<li class="list-group-item list-group-item-light">
							Announcements
						</li>
						<li class="list-group-item list-group-item-light">
							Calendars
						</li>
						<li class="list-group-item list-group-item-light">
							Etc.
						</li>
					</ul>
				</div>
			</div>
		</div>
	</main>
</body>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
	integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
	</script>
<script src="{{url_for('static', filename='js/jquery-3.5.1.js')}}"></script>
<script src="{{url_for('static', filename='js/bootstrap.js')}}"></script>
<script src="{{url_for('static', filename='js/sweetalert2.all.min.js')}}"></script>
<script src="{{url_for('static', filename='js/script.js')}}"></script>

</html>

cicksblog/templates/login.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}

		<legend class="display-4 mb-4">Login</legend>

		<div class="form-group">
			{{ form.username.label(class="form-control-label") }}
			{% if form.username.errors %}
			{{ form.username(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.username.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.username(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.password.label(class="form-control-label") }}
			{% if form.password.errors %}
			{{ form.password(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.password.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.password(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-check">
			{{ form.remember(class="form-check-input") }}
			{{ form.remember.label(class="form-check-label") }}
		</div>

		<div class="form-group mt-4 d-flex justify-content-between">
			{{ form.submit(class="btn btn-secondary") }}
			<small class="text-muted">
				<a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
			</small>
		</div>
	</form>
</div>

<div class="border-top border-secondary pt-2 mb-5">
	<small class="text-muted">
		Don't have an account?
		<a href="{{ url_for('users.registration') }}" class="ml-1">Sign Up</a>
	</small>
</div>

{% endblock content %}

cicksblog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}

        <legend class="display-4 mb-4">{{ legend }}</legend>

        <div class="form-group">
            {{ form.title.label(class="form-control-label") }}
            {% if form.title.errors %}
            {{ form.title(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.title.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.title(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group">
            {{ form.content.label(class="form-control-label") }}
            {% if form.content.errors %}
            {{ form.content(class="form-control form-control-lg is-invalid textarea-error") }}
            <div class="invalid-feedback">
                {% for error in form.content.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.content(class="form-control form-control-lg") }}
            {% endif %}
        </div>

        <div class="form-group mt-4">
            {{ form.submit(class="btn btn-secondary") }}
        </div>
    </form>
</div>

{% endblock content %}

cicksblog/templates/registration.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
	<form action="" method="POST">
		{{ form.hidden_tag() }}

		<legend class="display-4 mb-4">Create Your Account</legend>

		<div class="form-group">
			{{ form.username.label(class="form-control-label") }}
			{% if form.username.errors %}
			{{ form.username(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.username.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.username(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.email.label(class="form-control-label") }}
			{% if form.email.errors %}
			{{ form.email(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.email.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.email(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.phone_number.label(class="form-control-label") }}
			{% if form.phone_number.errors %}
			{{ form.phone_number(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.phone_number.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.phone_number(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.password.label(class="form-control-label") }}
			{% if form.password.errors %}
			{{ form.password(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.password.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.password(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group">
			{{ form.password_confirm.label(class="form-control-label") }}
			{% if form.password_confirm.errors %}
			{{ form.password_confirm(class="form-control form-control-lg is-invalid") }}
			<div class="invalid-feedback">
				{% for error in form.password_confirm.errors %}
				<span>{{ error }}</span>
				{% endfor %}
			</div>
			{% else %}
			{{ form.password_confirm(class="form-control form-control-lg") }}
			{% endif %}
		</div>

		<div class="form-group mt-4">
			{{ form.submit(class="btn btn-secondary") }}
		</div>
	</form>
</div>

<div class="border-top border-secondary pt-2 mb-5">
	<small class="text-muted">
		Already have an account?
		<a href="{{ url_for('users.login') }}" class="ml-1">Sign In</a>
	</small>
</div>

{% endblock content %}

cicksblog/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}

<!-- content -->
<h1 class="display-4 mb-2">
    Posts By {{ user.username }} ({{ posts.total }})
</h1>
{% for post in posts.items %}
<article class="media content-section">
    {% if post.author.id == current_user.id %}
    <a href="{{ url_for('users.account') }}" title="click to see your profile">
        <img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
    </a>
    {% else %}
    <a href="{{ url_for('users.account_info', username=post.author.username) }}" title="click to see this profile">
        <img class="rounded-circle article-img" src="{{url_for('static', filename='img/' + post.author.user_pict)}}">
    </a>
    {% endif %}
    <div class="media-body">
        <div class="article-metadata mb-2">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">
                {{ post.author.username }}
            </a>
            <small class="text-muted">{{ post.date_posted.strftime('%A, %d %b %Y.') }}</small>
        </div>
        <h3><a class="article-title" href="{{ url_for('posts.current_post', post_id=post.id) }}">{{ post.title }}</a>
        </h3>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}

<!-- pagination -->
<nav class="mt-2 mb-4" aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
        {% if page_num == posts.page %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
                {{ page_num }}
                <span class="sr-only">(current)</span>
            </a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
                {{ page_num }}
            </a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
    </ul>
</nav>

{% endblock content %}